### ISSUE TITLE
Make it possible to add more lines of one coin

### ISSUE THREAD

**Issue by nvomedia** [ErikBooij/CoinDashboard#1]
Nice tool! 
Is it possible to add multiple lines of one coin in the table? 
I have bought multiple times some cryptocurrencies with different investments, but only one line is shown up in the table..

**Comment by ErikBooij** [comment]
@nvomedia Excellent suggestion, made some changes: https://github.com/ErikBooij/CoinDashboard/tree/0.2

**Comment by nvomedia** [comment]
Nice! Beautiful changes! Also like the 'invested' column! Good work!
